### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by AndreaFavero71** [robertbates1995/CubePress#22]
Hi Robert, I'm Andrea Favero the CUBOTino inventor.
I'm very curious about your project.
Using the (Android) phone camera and calculation power is still on my todo list, but I got lost in other things.
I hope to see a CubePress video soon :-)

Regards
Andrea

**Comment by robertbates1995** [comment]
Closing this issue for clarity, but thank you for the kind words Andrea! :)
